-- AlterTable
ALTER TABLE `folder` ADD COLUMN `order` INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `instruction` ADD COLUMN `order` INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `step` ADD COLUMN `order` INTEGER NOT NULL DEFAULT 0;
